# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0905afdd022a0208d7551398ea44f5d6"
name = "admin-action-app"
handle = "admin-action-app-17"
application_url = "https://audio-h-sprint-polyphonic.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://audio-h-sprint-polyphonic.trycloudflare.com/auth/callback", "https://audio-h-sprint-polyphonic.trycloudflare.com/auth/shopify/callback", "https://audio-h-sprint-polyphonic.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
